const data =[
    {
        id: 0,
        name: 'CASIO MTP-1381L-1AVDF – NAM – QUARTZ (PIN) – DÂY DA',
        price: '1530',
        discriptions: 'Đồng hồ Casio MTP-1381L-1AVDF có vỏ kim loại bằng chất liệu thép không gỉ, nền số màu đen mạnh mẽ, kim chỉ và vạch số được phủ phản quang nổi bật, có thanh lịch thứ vị trí 12h và ô lịch ngày vị trí 6h.',
        picture: ['hinh_0_1.jpg', 'hinh_0_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất (Tùy từng lô hàng)'],
        informations_data: [
            'Casio',
            'MTP-1381L-1AVDF',
            'Nhật Bản',
            'Nam',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '39.9mm',
            '8.9 mm',
            ' ',
            'Dây Da Chính Hãng',
            'Đen',
            '5 ATM',
            'Lịch Ngày – Lịch Thứ',
            'Trung Quốc']},
    {
        id: 1,
        name: 'CASIO MW-240-4BVDF – NAM – KÍNH NHỰA – QUARTZ (PIN) – DÂY CAO SU – MẶT SỐ 43.6MM',
        price: '543',
        discriptions: 'Mẫu Casio MW-240-4BVDF mặt số đen size 43mm nổi bật lên nền cọc số học trò dày dặn phối tone màu cam với thiết kế năng động.',
        picture: ['hinh_1_1.jpg',
            'hinh_1_2.jpg',
            'hinh_1_3.jpg',
            'hinh_1_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất (Tùy từng lô hàng)'],
        informations_data: [
            'Casio',
            'MW-240-4BVDF',
            'Nhật Bản',
            'Nam',
            'Resin Glass (Kính Nhựa)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '43.6 mm',
            '10.3 mm',
            ' ',
            'Dây Cao Su',
            'Đen',
            '5 ATM',
            ' ',
            'Trung Quốc']},
    {
        id: 2,
        name: 'LONGINES L2.628.5.19.7 – NAM – KÍNH SAPPHIRE – AUTOMATIC (TỰ ĐỘNG) – DÂY KIM LOẠI – MẶT SỐ 38.5MM',
        price: '78320',
        discriptions: 'Mẫu Longines L2.628.5.19.7 phiên bản kim chỉ xanh tone màu thời trang nổi bật trên nền mặt số trắng size 38.5mm, thiết kế trẻ trung với nền cọc số la mã tạo hình mỏng cách tân.',
        picture: ['hinh_2_1.jpg', 'hinh_2_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Longines',
            'L2.628.5.19.7',
            'Thụy Sỹ',
            'Nam',
            'Sapphire (Kính Chống Trầy)',
            'Automatic (Tự Động)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '35.8 mm',
            '9.2 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Trắng',
            '3 ATM',
            'Lịch Ngày',
            'Thụy Sỹ']},
    {
        id: 3,
        name: 'CASIO MTP-V300L-1A3UDF – NAM – QUARTZ (PIN) – DÂY DA',
        price: '1530',
        discriptions: 'Mẫu Casio MTP-V300L-1A3UDF phiên bản nền cọc số la mã tạo hình mỏng trẻ trung trên nền mặt số đen size 41mm phối cùng mẫu dây da trơn.',
        picture: ['hinh_3_1.jpg',
            'hinh_3_2.jpg',
            'hinh_3_3.jpg',
            'hinh_3_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng'],
        informations_data: [
            'Casio',
            'MTP-V300L-1A3UDF',
            'Nhật Bản',
            'Nam',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '41.5 mm',
            '8.6 mm',
            ' ',
            'Dây Da Chính Hãng',
            'Đen',
            '3 ATM',
            'Lịch Ngày – Lịch Thứ – Đồng Hồ 24 Giờ']},
    {
        id: 4,
        name: 'TISSOT T063.409.16.058.00 – NAM – KÍNH SAPPHIRE – QUARTZ (PIN) – DÂY DA',
        price: '9790',
        discriptions: 'Mẫu Tissot T063.409.16.058.00 dây đeo da tạo hình vân cá sấu tone đen mang lại vẻ lịch lãm không kém cạnh trẻ trung với nền cọc số la mã kiểu dáng mỏng.',
        picture: ['hinh_4_1.jpg', 'hinh_4_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Tissot',
            'T063.409.16.058.00',
            'Thụy Sỹ',
            'Nam',
            'Sapphire (Kính Chống Trầy)',
            'Quartz (Pin)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '39 mm',
            '5.2 mm',
            'Thép Không Gỉ',
            'Dây Da Chính Hãng',
            'Đen',
            '3 ATM',
            ' ',
            'Thụy Sỹ']},
    {
        id: 5,
        name: 'CASIO MTP-V004L-3BUDF – NAM – QUARTZ (PIN) – DÂY DA – MẶT SỐ 41.5MM',
        price: '765',
        discriptions: 'Mẫu Casio MTP-V004L-3BUDF dây da phiên bản da trơn phối tone màu xanh trẻ trung, cùng với lối thiết kế đơn giản chức năng 3 kim trên nền mặt số trắng size 41mm.',
        picture: ['hinh_5_1.jpg',
            'hinh_5_2.jpg',
            'hinh_5_3.jpg',
            'hinh_5_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất (Tùy từng lô hàng)'],
        informations_data: [
            'Casio',
            'MTP-V004L-3BUDF',
            'Nhật Bản',
            'Nam',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '41.5 mm',
            '8.3 mm',
            ' ',
            'Dây Da Chính Hãng',
            'Trắng',
            '3 ATM',
            'Lịch Ngày',
            'Trung Quốc']},
    {
        id: 6,
        name: 'LONGINES L1.611.4.52.2 – NAM – KÍNH SAPPHIRE – AUTOMATIC (TỰ ĐỘNG) – DÂY DA',
        price: '30800',
        discriptions: 'Mẫu L1.611.4.52.2 vẻ ngoài giản dị tinh tế với chi tiết vạch số được gia công tạo hình dày dặn bao phủ tông vàng hồng tạo nên yếu tố của vẻ sang trọng đến từ thương hiệu Longines, lịch lãm.',
        picture: ['hinh_6_1.jpg', 'hinh_6_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Longines',
            'L1.611.4.52.2',
            'Thụy Sỹ',
            'Nam',
            'Sapphire (Kính Chống Trầy)',
            'Automatic (Tự Động)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '35 mm',
            '7 mm',
            'Thép Không Gỉ',
            'Dây Da Chính Hãng',
            'Đen',
            '3 ATM',
            'Lịch Ngày',
            'Thụy Sỹ']},
    {
        id: 7,
        name: 'TISSOT T038.430.11.057.00 – NAM – KÍNH SAPPHIRE – AUTOMATIC (TỰ ĐỘNG) – DÂY KIM LOẠI',
        price: '18610',
        discriptions: 'Đồng hồ Tissot T038.430.11.057.00 mang lại nét sang trọng trong từng chi tiết, với thiết kế nền đen mặt số, kim chỉ và gạch số mỏng, dây đeo kim loại chắc chắn mang lại cho phái mạnh vẻ nam tính, lịch lãm.',
        picture: ['hinh_7_1.jpg',
            'hinh_7_2.jpg',
            'hinh_7_3.jpg',
            'hinh_7_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Tissot',
            'T038.430.11.057.00',
            'Thụy Sỹ',
            'Nam',
            'Sapphire (Kính Chống Trầy)',
            'Automatic (Tự Động)',
            '2 Năm',
            '4 Năm – RED Guarantee ',
            '38.5 mm',
            '9.8 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Đen',
            '5 ATM',
            'Lịch Ngày',
            'Thụy Sỹ']},
    {
        id: 8,
        name: 'LONGINES L2.755.5.97.7 – NAM – KÍNH SAPPHIRE – AUTOMATIC (TỰ ĐỘNG) – DÂY KIM LOẠI',
        price: '90860',
        discriptions: 'Đồng hồ Longines L2.755.5.97.7 trải nghiệm với bộ máy cơ dành cho nam, dưới mặt kính Sapphire cao cấp với thiết kế đính kèm các viên kim cương trên nền mặt số tôn lên vẻ sang trọng.',
        picture: ['hinh_8_1.jpg', 'hinh_8_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Longines',
            'L2.755.5.97.7',
            'Thụy Sỹ',
            'Nam',
            'Sapphire (Kính Chống Trầy)',
            'Automatic (Tự Động)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '38.5 mm',
            '9.5 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Trắng',
            '3 ATM',
            'Lịch Ngày – Lịch Thứ',
            'Thụy Sỹ']},
    {
        id: 9,
        name: 'G-SHOCK G-8900CS-3DR – NAM – QUARTZ (PIN) – DÂY CAO SU',
        price: '3430',
        discriptions: 'Đồng hồ G-Shock G-8900CS-3DR với vỏ và dây đeo làm bằng nhựa cao cấp, màu xanh của vỏ kết hợp cùng màu trắng của dây đeo đem đến nét trẻ trung năng động cho giới trẻ, có 4 nút tùy chỉnh chế độ thuận tiện.',
        picture: ['hinh_9_1.jpg',
            'hinh_9_2.jpg',
            'hinh_9_3.jpg',
            'hinh_9_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất (Tùy từng lô hàng)'],
        informations_data: [
            'Casio',
            'G-8900CS-3DR',
            'Nhật Bản',
            'Nam',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '5 Năm',
            ' ',
            '55.1mm\u2002×\u200252.5mm',
            '16.3 mm',
            'Nhựa',
            'Dây Cao Su',
            'Xanh',
            '20 ATM',
            'Lịch – Bộ Bấm Giờ – Giờ Thế Giới – Đèn Led – Vài Chức Năng Khác',
            'Trung Quốc']},
    {
        id: 10,
        name: 'SKAGEN SKW2839 – NỮ – QUARTZ (PIN) – DÂY DA – MẶT SỐ 30MM',
        price: '2340',
        discriptions: 'Mẫu Skagen SKW2839 dây da phiên bản dây da trơn phối tone màu kem thời trang cho phái đẹp cùng với thiết kế tối giản chức năng 2 kim trên nền mặt số size 30mm.',
        picture: ['hinh_10_1.jpg',
            'hinh_10_2.jpg',
            'hinh_10_3.jpg',
            'hinh_10_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng'],
        informations_data: [
            'Skagen',
            'SKW2839',
            'Đan Mạch',
            'Nữ',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '2 Năm',
            ' ',
            '30 mm',
            '6 mm',
            'Thép Không Gỉ',
            'Dây Da Chính Hãng',
            'Trắng',
            '3 ATM',
            ' ']},
    {
        id: 11,
        name: 'BABY-G BLX-560-7DR – NỮ – QUARTZ (PIN) – DÂY CAO SU',
        price: '2912',
        discriptions: 'Mẫu Baby-G BLX-560-7DR phiên bản dây vỏ trắng thời trang phối cùng mặt số điện tử đa chức năng, vỏ máy nhựa dày dặn với khả năng chịu nước 20atm.',
        picture: ['hinh_11_1.jpg',
            'hinh_11_2.jpg',
            'hinh_11_3.jpg',
            'hinh_11_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng'],
        informations_data: [
            'Casio',
            'BLX-560-7DR',
            'Nhật Bản',
            'Nữ',
            'Resin Glass (Kính Nhựa)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '44.7 mm x 40 mm',
            '12.5 mm',
            'Nhựa',
            'Dây Cao Su',
            'Trắng',
            '20 ATM',
            'Lịch – Bộ Bấm Giờ – Giờ Kép – Đèn Led – Vài Chức Năng Khác']},
    {
        id: 12,
        name: 'MOVADO 3600435 – NỮ – QUARTZ (PIN) – DÂY KIM LOẠI',
        price: '19400',
        discriptions: 'Mẫu 3600435 thiết kế sang trọng với sự kết hợp giữa vỏ máy cùng dây đeo bằng kim loại màu vàng hồng sang trọng, đồng hồ với thiết kế 2 kim đặc trưng đến từ hãng Movado.',
        picture: ['hinh_12_1.jpg',
            'hinh_12_2.jpg',
            'hinh_12_3.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Movado',
            '3600435',
            'Thụy Sỹ',
            'Nữ',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '30 mm',
            '11 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Vàng Hồng',
            '3 ATM',
            ' ',
            'Thụy Sỹ']},
    {
        id: 13,
        name: 'CASIO LRW-200H-4E3VDF – NỮ – KÍNH NHỰA – QUARTZ (PIN) – DÂY CAO SU',
        price: '815',
        discriptions: 'Mẫu Casio LRW-200H-4E3VDF thiết kế dây vỏ nhựa tone màu trắng năng động, mặt số đơn giản size 34mm kiểu dáng 3 kim 1 lịch.',
        picture: ['hinh_13_1.jpg',
            'hinh_13_2.jpg',
            'hinh_13_3.jpg',
            'hinh_13_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng'],
        informations_data: [
            'Casio',
            'LRW-200H-4E3VDF',
            'Nhật Bản',
            'Nữ',
            'Resin Glass (Kính Nhựa)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '34.2 mm',
            '11.5 mm',
            ' ',
            'Dây Cao Su',
            'Hồng',
            '10 ATM',
            'Lịch Ngày']},
    {
        id: 14,
        name: 'CITIZEN PD7156-58P – NỮ – KÍNH SAPPHIRE – AUTOMATIC (TỰ ĐỘNG) – DÂY KIM LOẠI – MẶT SỐ 29MM',
        price: '9220',
        discriptions: 'Mẫu Citizen PD7156-58P phiên bản dây đeo vàng demi vẻ ngoài thời trang sang trọng cho phái đẹp, cùng với thiết kế đơn giản chức năng 3 kim.',
        picture: ['hinh_14_1.jpg', 'hinh_14_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng'],
        informations_data: [
            'Citizen',
            'PD7156-58P',
            'Nhật Bản',
            'Nữ',
            'Sapphire (Kính Chống Trầy)',
            'Automatic (Tự Động)',
            '1 Năm',
            '5 Năm',
            '29 mm',
            '10.5 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Vàng',
            '5 ATM',
            'Lịch Ngày – Lịch Thứ']},
    {
        id: 15,
        name: 'CASIO LRW-200H-2BVDF – NỮ – KÍNH NHỰA – QUARTZ (PIN) – DÂY CAO SU',
        price: '815',
        discriptions: 'Mẫu Casio LRW-200H-2BVDF vẻ ngoài thời trang với phần thiết kế vỏ viền ngoài phối tông màu xanh kết hợp cùng mẫu dây đeo cao su trắng mang lại vẻ cá tính dành cho các bạn trẻ, ấn tượng với khả năng chịu nước lên đến 10ATM.',
        picture: ['hinh_15_1.jpg',
            'hinh_15_2.jpg',
            'hinh_15_3.jpg',
            'hinh_15_4.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất (Tùy từng lô hàng)'],
        informations_data: [
            'Casio',
            'LRW-200H-2BVDF',
            'Nhật Bản',
            'Nữ',
            'Resin Glass (Kính Nhựa)',
            'Quartz (Pin)',
            '1 Năm',
            ' ',
            '34.2 mm',
            '11.5 mm',
            'Nhựa',
            'Dây Cao Su',
            'Trắng',
            '10 ATM',
            'Lịch Ngày',
            'Trung Quốc']},
    {
        id: 16,
        name: 'FOSSIL ES4511 – NỮ – QUARTZ (PIN) – DÂY KIM LOẠI – MẶT SỐ 36MM',
        price: '3750',
        discriptions: 'Mẫu Fossil ES4511 với các chi tiết kim chỉ cùng cọc vạch số được tạo nét thanh mảnh nữ tính trên mặt số đen size 36mm.',
        picture: ['hinh_16_1.jpg', 'hinh_16_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Fossil',
            'ES4511',
            'Mỹ',
            'Nữ',
            'Mineral Crystal (Kính Cứng)',
            'Quartz (Pin)',
            '2 Năm',
            '5 Năm',
            '36 mm',
            '8 mm',
            'Thép Không Gỉ',
            'Thép Không Gỉ',
            'Đen',
            '5 ATM',
            ' ',
            'Trung Quốc']},
    {
        id: 17,
        name: 'TISSOT T035.210.16.031.00 – NỮ – KÍNH SAPPHIRE – QUARTZ (PIN) – DÂY DA – MẶT SỐ 32MM',
        price: '9070',
        discriptions: 'Mẫu Tissot T035.210.16.031.00 dây da tạo hình vân thanh lịch phiên bản dây da tone màu trắng trẻ trung kết hợp cùng với lối thiết kế đơn giản chức năng 3 kim trên nền mặt số size 32mm.',
        picture: ['hinh_17_1.jpg', 'hinh_17_2.jpg'],
        informations_name: [
            'Thương Hiệu',
            'Số Hiệu Sản Phẩm',
            'Xuất Xứ',
            'Giới Tính',
            'Kính',
            'Máy',
            'Bảo Hành Quốc Tế',
            'Bảo Hành Tại Hải Triều',
            'Đường Kính Mặt Số',
            'Bề Dày Mặt Số',
            'Niềng',
            'Dây Đeo',
            'Màu Mặt Số',
            'Chống Nước',
            'Chức Năng',
            'Nơi sản xuất'],
        informations_data: [
            'Tissot',
            'T035.210.16.031.00',
            'Thụy Sỹ',
            'Nữ',
            'Sapphire (Kính Chống Trầy)',
            'Quartz (Pin)',
            '2 Năm',
            '4 Năm – RED Guarantee',
            '32 mm',
            '8.1 mm',
            'Thép Không Gỉ',
            'Dây Da Chính Hãng',
            'Trắng',
            '10 ATM',
            'Lịch Ngày',
            'Thụy Sỹ']},
];
